import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { AlertTriangle, ArrowLeft } from "lucide-react";

const FinancialDisclaimer = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Button variant="ghost" className="mb-6 gap-2" onClick={() => navigate(-1)}>
          <ArrowLeft className="h-4 w-4" /> Back
        </Button>

        <div className="flex items-center gap-3 mb-2">
          <AlertTriangle className="h-8 w-8 text-yellow-500" />
          <h1 className="text-3xl font-bold">Financial Disclaimer</h1>
        </div>
        <p className="text-muted-foreground text-sm mb-8">Last updated: March 2026</p>

        <div className="rounded-lg border border-yellow-500/30 bg-yellow-500/5 p-5 mb-8">
          <p className="font-semibold text-yellow-600 dark:text-yellow-400">
            ⚠️ IMPORTANT: InvestoraAI is NOT a licensed financial adviser. All content is for
            informational and educational purposes only.
          </p>
        </div>

        <div className="space-y-8 text-sm leading-7 text-foreground/90">
          <section>
            <h2 className="text-lg font-semibold mb-2">1. Not Financial Advice</h2>
            <p>
              The information, analysis, sentiment scores, alerts, and reports provided by
              InvestoraAI do not constitute financial advice, investment advice, trading advice,
              or any other type of advice. You should not treat any content on this platform as
              such.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">2. AI-Generated Content</h2>
            <p>
              All analysis is generated by artificial intelligence (OpenAI GPT-4 and LangChain
              agents). AI models can make errors, hallucinate information, or produce inaccurate
              assessments. <strong>Never make financial decisions based solely on AI-generated
              content.</strong>
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">3. No Guarantee of Accuracy</h2>
            <p>
              While we strive to provide accurate and timely information, InvestoraAI makes no
              warranties about the completeness, accuracy, reliability, or suitability of the
              information for any particular purpose. Financial markets are volatile and
              unpredictable.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">4. Investment Risk</h2>
            <p>
              All investments involve risk, including the possible loss of principal. Past
              performance is not indicative of future results. The value of investments can go
              down as well as up.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">5. Consult a Professional</h2>
            <p>
              Before making any investment decisions, please consult a qualified financial adviser,
              accountant, or legal professional who is aware of your personal financial situation
              and goals.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">6. Regulatory Compliance</h2>
            <p>
              InvestoraAI is not registered with any financial regulatory authority. Users are
              responsible for ensuring compliance with the financial laws and regulations
              applicable in their jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">7. Limitation of Liability</h2>
            <p>
              InvestoraAI, its creators, and contributors shall not be held liable for any
              financial losses, damages, or other consequences arising from your reliance on
              information provided through this platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">8. Contact</h2>
            <p>
              For questions about this disclaimer, contact us at{" "}
              <a href="mailto:legal@investoraai.com" className="text-primary underline">
                legal@investoraai.com
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-10 text-center">
          <Button onClick={() => navigate("/")} className="gap-2">
            I Understand — Return to Dashboard
          </Button>
        </div>
      </div>
    </div>
  );
};

export default FinancialDisclaimer;
